server:
  port: 8082

# database 연동 설정
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: team4
    password: 1234
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create